name: Sammons Lab Research
description: Science updates from the Sammons lab at the University at Albany, SUNY
url: http://sammonslab.org

markdown: kramdown
permalink: /:categories/:title/
future: true
sass:
  sass_dir: css

plugins:
  - jekyll-gzip
  - jekyll-twitter-plugin

gzip:
  replace_files: true

exclude:
  - "*.branches"
  - "*.class"
  - "*.cpp"
  - "*.csv"
  - "*.fasta"
  - "*.gz"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.nb"
  - "*.newick"
  - "*.nex"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.tiff"
  - "*.tips"
  - "*.trees"
  - "*.tsv"
  - "*.txt"
  - "*.xml"
  - "*.zip"
  - "Gemfile"
  - "Gemfile.lock"


readmes:
 
projects:
 