name: Sammons Lab Research
description: Science updates on transcription factors, chromatin, and p53 biology from the Sammons Lab at the State University of New York at Albany

markdown: redcarpet
permalink: /:categories/:title/
future: true

redcarpet:
  extensions:
   - tables
   - no_intra_emphasis
   - autolink
   - superscript
   - strikethrough

exclude:
  - vendor
  - "*.class"
  - "*.cpp"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.nb"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.branches"
  - "*.csv"
  - "*.fasta"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.newick"
  - "*.nex"
  - "*.tsv"
  - "*.tips"
  - "*.trees"
  - "*.txt"
  - "*.zip"
  - "*.gz"
  - "Gemfile"
  - "Gemfile.lock"
 

projects:
 
